shop/accounts/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('create/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

shop/books/urls.py
from django.urls import path, include
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.index),
    path('<int:book_id>/view', views.book, name='view'),
    path('<int:book_id>/buy', views.buy_book, name='buy'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('books.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('accounts.urls')),
]

shop/accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    photo = models.ImageField(upload_to=f'users/{user}', blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    biography = models.TextField(blank=True)
    
    def __str__(self) -> str:
        return f'{self.user.username}\'s Profile.'
    

shop/books/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Genre(models.Model):
    name = models.CharField(max_length=100, help_text="Enter genre name")

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=False)
    date_of_death = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class Book(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(help_text="Enter short description")
    genre = models.ManyToManyField(Genre, help_text="Select a genre")
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    count = models.IntegerField(default=0)
    price = models.FloatField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('books:view', args=[str(self.id)])
    
    def genres(self):
        return ','.join([genre.name for genre in self.genre.all()])

    
class BuyBook(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    home = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}\'s order'

shop/cart/models.py
from django.db import models

# Create your models here.

shop/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput)
    email = forms.CharField(label='Email', widget=forms.EmailInput)
    first_name = forms.CharField(label='First name', widget=forms.TextInput)
    last_name = forms.CharField(label='Last name', widget=forms.TextInput)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
       
    class Meta:
        model = User
        fields = ('username','email', 'first_name', 'last_name', 'password')
        
    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError('Passwords didn\'t match!')
        return data['password2']
    
   
class UserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name')
        
    
class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ('photo', 'date_of_birth', 'biography')

shop/books/forms.py
from pyexpat import model
from django import forms
from .models import BuyBook

class BuyBookForm():
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    phone_number = forms.IntegerField(label='Phone number')
    city = forms.CharField(label='City')
    street = forms.CharField(label='Street')
    home = forms.CharField(label='Home')
    
    class Meta:
        models = BuyBook
        fields = ('first_name', 'last_name', 'phone_number', 'city', 'street', 'home')

shop/accounts/views.py
from django.shortcuts import render
from .forms import UserRegistrationForm, UserForm, ProfileForm
from .models import Profile
from django.contrib.auth.decorators import login_required

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        # profile_form = UserForm()
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request, 'registration/registration_done.html')
        return render(request, 'registration/registration.html', {'user_form': user_form})
    
    return render(request, 'registration/registration.html', {'user_form': UserRegistrationForm()})


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserForm(instance=request.user, data=request.POST)
        profile_form = ProfileForm(instance=request.user.profile, data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'registration/profile.html', {'user_form': user_form, 'profile_form': profile_form})

shop/books/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Book, Author, Genre, BuyBook
from .forms import BuyBookForm
from django.contrib.auth.decorators import login_required


def about_shop(req):
    visits = req.session.get('visits', 0)
    books_amount = Book.objects.count()
    author_amount = Author.objects.count()
    return {'books_amount': books_amount,
            'author_amount': author_amount,
            'visits': visits}

def index(request):
    atr_dictionary = about_shop(request)
    request.session['visits'] = request.session.get('visits', 0) + 1
    books = Book.objects.all()
    atr_dictionary['books'] = books
    return render(request, 'index.html', atr_dictionary)

def book(request, book_id):
    atr_dictionary = about_shop(request)
    atr_dictionary['book'] = Book.objects.get(id=book_id)
    return render(request, 'book.html', atr_dictionary)

def buy_book(request, book_id):
    book = Book.objects.get(id=book_id)
    if request.method == 'POST':
        buy_form = BuyBookForm(request.POST, user=request.user)
        if buy_form.is_valid():
            order = buy_form.save(commit=False)
            order.save()
            return HttpResponseRedirect(reverse('index'))
        return render(request, 'buy.html', {'book': book, 'buy_form': buy_form})
    return render(request, 'buy.html', {'book': book, 'buy_form': BuyBookForm()})



    #         BuyBook.objects.create(BuyBook=order)
            
    # atr_dictionary = about_shop(request)
    # atr_dictionary['book'] = Book.objects.get(id=book_id)
    # return render(request, 'buy_book.html', atr_dictionary)

shop/cart/views.py
from django.shortcuts import render

# Create your views here.

shop/books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookShop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <div class="bg-dark collapse" id="navbarHeader">
          <div class="container">
            <div class="row">
              <div class="col-sm-8 col-md-7 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">Visits: {{visits}}</p>
                <p class="text-muted">Author: {{author_amount}}</p>
                <p class="text-muted">Books amount: {{books_amount}}</p>
              </div>
              <div class="col-sm-4 offset-md-1 py-4">
                <h4 class="text-white">Contact</h4>
                <ul class="list-unstyled">
                  <li><a href="#" class="text-white">Follow on Twitter</a></li>
                  <li><a href="#" class="text-white">Like on Facebook</a></li>
                  <li><a href="#" class="text-white">Email me</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="navbar navbar-dark bg-dark box-shadow">
          <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
              <strong>Book Store</strong>
            </a>
            <div class="navbar-toggler">
              {% if user.is_authenticated %}
                <span><a href="{% url 'logout' %}" role="button" class="btn btn-outline-secondary">My profile</a></span>
                <span>Welcome back, {{ user.get_username }}!<a href="{% url 'logout' %}" role="button" class="btn btn-outline-secondary">Log out</a></span>
                
              {% else %}
                <a href="{% url 'login' %}" role="button" class="btn btn-outline-secondary">Sign in</a>
                <a href="{% url 'register' %}" role="button" class="btn btn-outline-secondary">Sign up</a>
              {% endif %}
              <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          </div>
        </div>
    </header>
    <div class='container'>
      {% block content %} {% endblock %}
    </div>
</body>
</html>

shop/books/templates/book.html
{% extends 'base.html' %} {% block content %}
<div class="text-center">
    <img
            class="card-img-top"
            data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
            alt="Thumbnail [100%x225]"
            style="height: 225px; width: 100%;"
            src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_18144654ce8%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_18144654ce8%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.71875%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
            data-holder-rendered="true"
        />
</div>
<div class="justify-content-md-center">
    <div class="card mb-4 box-shadow">
        
        <div class="card-body">
            <h1 class="card-text">
                {{book.title}}
            </h1>
            <h3 class="card-text">
                Author: {{book.author}}
            </h3>
            <p class="card-text">Description: {{book.description}}</p>
            <p class="card-text">Genres: {{book.genres}}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    {% if book.count != 0 %}
                    <form method="get">
                        <a href="{% url 'books:buy' book.id %}" role="button" class="btn btn-sm btn-outline-secondary" >Buy</a>
                    </form>
                    {% else %}
                    <button type="button" class="btn btn-sm btn-outline-secondary disabled">Out of stock!</button>
                    {% endif %}
                </div>
                <small class="text-muted">{{book.price}}</small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/books/templates/buy_book.html
{% extends 'base.html' %}
{% block content %}
<form class="row g-3 needs-validation" novalidate>
    <!-- <div class="col-md-4 position-relative">
      <label for="validationTooltip01" class="form-label">First name</label>
      <input type="text" class="form-control" id="validationTooltip01" value="Mark" required>
      <div class="valid-tooltip">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 position-relative">
      <label for="validationTooltip02" class="form-label">Last name</label>
      <input type="text" class="form-control" id="validationTooltip02" value="Otto" required>
      <div class="valid-tooltip">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 position-relative">
      <label for="validationTooltipUsername" class="form-label">Username</label>
      <div class="input-group has-validation">
        <span class="input-group-text" id="validationTooltipUsernamePrepend">@</span>
        <input type="text" class="form-control" id="validationTooltipUsername" aria-describedby="validationTooltipUsernamePrepend" required>
        <div class="invalid-tooltip">
          Please choose a unique and valid username.
        </div>
      </div>
    </div>
    <div class="col-md-6 position-relative">
      <label for="validationTooltip03" class="form-label">City</label>
      <input type="text" class="form-control" id="validationTooltip03" required>
      <div class="invalid-tooltip">
        Please provide a valid city.
      </div>
    </div>
    <div class="col-md-3 position-relative">
      <label for="validationTooltip04" class="form-label">State</label>
      <select class="form-select" id="validationTooltip04" required>
        <option selected disabled value="">Choose...</option>
        <option>...</option>
      </select>
      <div class="invalid-tooltip">
        Please select a valid state.
      </div>
    </div>
    <div class="col-md-3 position-relative">
      <label for="validationTooltip05" class="form-label">Zip</label>
      <input type="text" class="form-control" id="validationTooltip05" required>
      <div class="invalid-tooltip">
        Please provide a valid zip.
      </div>
    </div> -->
    {% csrf_token %}
    <div class="col-12">
      <button class="btn btn-primary" type="submit">Submit form</button>
    </div>
  </form>
  {% endblock %}

shop/books/templates/index.html
{% extends 'base.html' %} 
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for book in books %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img
                        class="card-img-top"
                        data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
                        alt="Thumbnail [100%x225]"
                        style="height: 225px; width: 100%; display: block"
                        src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20225%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_18144654ce8%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_18144654ce8%22%3E%3Crect%20width%3D%22348%22%20height%3D%22225%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.71875%22%20y%3D%22120.3%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                        data-holder-rendered="true"
                    />
                    <div class="card-body">
                        <p class="card-text">
                            {{book.title}}
                        </p>
                        <p class="card-text">
                            {{book.author}}
                        </p>
                        <div
                            class="d-flex justify-content-between align-items-center"
                        >
                            <div class="btn-group">
                                <form method="get">
                                <a href="{{book.get_absolute_url}}"
                                    role="button"
                                    class="btn btn-sm btn-outline-secondary"
                                >
                                    View
                                </a>
                                </form>
                            </div>
                            <small class="text-muted">{{book.price}}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}